package com.example.phoenixdroid.proyectoinge2.Utils;

public enum Zona {
    SALIDA_QUEBRADA_PITIER, QUEBRADA_TAPEZCO, QUEBRADA_SANGIJUELA, QUEBRADA_CANOAS, QUEBRADA_NAVAJAS, PUENTE_SECTOR_LA_FUENTE,
    PASO_MACHETE, MATINILLA, ENTRADA_CALLE_LOS_ALVAREZ, CRUCE_PABELLON, CALLE_PARALELA_RIO_URUCA, CALLE_LOS_DELGADO, CALLE_LA_CANADA;
}
